### ISSUE TITLE
Not working in Avalonia 11.0.1

### ISSUE THREAD

**Issue by Kokoreff081** [arklumpus/AvaloniaColorPicker#12]
I used your amazing ColorPicker in avalonia 0.10, but after updating avalonia version it broken. 
Main error is:
ColorPickerWnd.axaml.cs(65, 15): [CS0012] The type 'Color' is defined in an unreferenced assembly. You should add a reference to the assembly "Avalonia.Visuals, Version=0.10.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b".

Can you make an update to your ColorPicker?

**Comment by arklumpus** [comment]
Hi, I just pushed version 1.4.0, which requires Avalonia 11.0.1. Let me know if you spot any issues!

**Comment by Kokoreff081** [comment]
So, i tried to update to 1.4.0, and found 
![image](https://github.com/arklumpus/AvaloniaColorPicker/assets/31157426/c509f52f-879a-4e3a-82d4-fed06272307d)
![image](https://github.com/arklumpus/AvaloniaColorPicker/assets/31157426/8bf279aa-4a01-4f39-ae4d-b7368bd6c809)
SO, is there information about ColorPickerWindow and its properly working implementation?

**Comment by arklumpus** [comment]
It's working fine for me, you're getting `null` probably because you're trying to access the members before the call to `InitializeComponent`. This method is responsible for loading the XAML template and populating the fields, hence you cannot access stuff that has been declared in the XAML code before `InitializeComponent` is called.

In the constructor, try moving the lines:

```CSharp
var cp = DmxColorPicker;
var cp2 = ...
```

After the call to `this.InitializeComponent();`

**Comment by Kokoreff081** [comment]
So, it was my mistake, now it working properly.
Thanks again!
