### ISSUE TITLE
1.3.1 doesn't work

### ISSUE THREAD

**Issue by antontuz** [arklumpus/AvaloniaColorPicker#5]
I tried to use color picker but I got the error - **System.InvalidOperationException: This operation is not supported for a relative URI**. How to fix it? 
![image](https://user-images.githubusercontent.com/50873585/160367092-4a93a747-b1cc-4bb6-9495-5f4294b72d09.png)

**Comment by antontuz** [comment]
https://github.com/arklumpus/AvaloniaColorPicker/blob/main/AvaloniaColorPicker/Colours.cs#L97-L107
I don't have `<FluentTheme Mode="Light"/>` in my code that is why I get **System.InvalidOperationException: This operation is not supported for a relative URI.**

**Comment by arklumpus** [comment]
Hi, thanks for noticing this!

The real issue is that you must have a `StyleInclude` in the `App.xaml` file, that references a style file using a relative source Uri (e.g., you have `<StyleInclude Source="/Asset.xaml"/>` instead of `<StyleInclude Source="avares://YourAssemblyName/Asset.xaml"/>`). As a result, when that code tries to access the `AbsoluteUri` property of the `Source` Uri object, an exception is thrown.

This should be fixed in version 1.3.2, please have a look at that!

**Comment by antontuz** [comment]
works good! Thanks for quick fix, I appreciate that
