### ISSUE TITLE
`ColorPickerWindow` does not have a minimum size

### ISSUE THREAD

**Issue by colejohnson66** [arklumpus/AvaloniaColorPicker#8]
See this screenshot:

![image](https://user-images.githubusercontent.com/11381599/178308691-8f74f706-a522-4b28-beb1-761afdb911c5.png)

**Comment by colejohnson66** [comment]
In addition, if I maximize the window, there's no growth at all into the available space. Maybe a `Viewbox` or `CanResize="False"` should be added to the window?

![image](https://user-images.githubusercontent.com/11381599/178309270-c4af9f1b-dbcb-40e4-aa4d-361ee054a2d0.png)

**Comment by arklumpus** [comment]
Hi, thank you for this! I have added `CanResize="False"` to the `ColorPickerWindow`.

Note that if you want a more flexible behaviour, you can either [create a new `Window` implementing `IColorPickerWindow`](https://github.com/arklumpus/AvaloniaColorPicker/wiki/Customising-the-colour-picker-window) and put a `ColorPicker` control inside it (e.g. within a `ViewBox`, if you want), or [create a `CustomColorPicker` with a completely different layout](https://github.com/arklumpus/AvaloniaColorPicker/wiki/Creating-a-custom-colour-picker) (which would let you e.g. allow the controls to grow to fill the available space).

Neither of these is the default because with the `ViewBox` the buttons would become too small to click on them, and with the dynamic layout things can get messy very quickly if you're not careful.
