### ISSUE TITLE
Rename "Wong" palette

### ISSUE THREAD

**Issue by colejohnson66** [arklumpus/AvaloniaColorPicker#9]
The Wong palette appears to have been copied into their publication without attribution from [Masataka Okabe & Kei Ito in 2002](https://jfly.uni-koeln.de/color/). See also: https://github.com/matplotlib/matplotlib/issues/9460

**Comment by arklumpus** [comment]
Thank you for this. I have renamed the Wong palette to "Okabe-Ito", with description "Okabe and Ito's color-blind barrier free palette, from https://jfly.uni-koeln.de/color/". Let me know if you have any other suggestions on this.

Note that the library creates the palette folder the first time it is run on a system; therefore, for systems where the Wong palette has already been created, the existing Wong palette file needs to be removed and replaced with the new file. The library does this automatically, as long as the Wong palette file is exactly 186 bytes long (taken as a proxy of the fact that the user has not modified the palette). If the Wong palette has been modified by the user (as evidenced by the fact that the file size is not 186 bytes anymore), it is not touched by the library. This seems to me an acceptable compromise between scientific integrity and inconvenience to the end-user, but let me know if you have a better idea.

In any case, I would *strongly* recommend that you (or the person who first noticed this) report the plagiarism issue to the journal where the Wong paper has been published. This is both so that appropriate steps can be taken, proportional to the impact of the plagiarism (would the paper have received that many citations, had the palette not been included, or had it been properly referenced?), and so that a proper investigation can be conducted (the plagiarism appears evident; however, the author should be given the possibility to defend his actions).
